name: Update Readme

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 12 * * *"

jobs:
  updation:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repository
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install PIP Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update README
        run: |
          cd src
          python main.py
          cd ..

      - name: Commit and Push
        run: |
          readme_file='readme.md'
          change=`git diff $readme_file`
          if [ ! -z "$change" ]; then
            git config user.name "Github Actions" 
            git config user.email noreply@github.com
            git add $readme_file
            git commit -m "chore: updated $readme_file"
            git push origin master --force
          fi
