name: Update Readme

on:
  push:
    branches:
      - master
  schedule:
    - cron: "30 17 * * *" # Since I was born at 11PM IST

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name: Cache PIP Dependencies
        id: cache-pip-dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation}}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install Dependencies if not cached
        if: steps.cache-pip-dependencies.outputs.cache-hit != 'true'
        run: |-
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update README
        run: |-
          python src/main.py

      - name: Commit and Push
        run: |-
          readme_file="readme.md"
          if [ $(git status $readme_file --porcelain=v1 2>/dev/null | wc -l) != "0" ] ; then
            git config user.name "Github Actions" 
            git config user.email noreply@github.com
            git add $readme_file
            git commit -m "chore: updated $readme_file"
            git push origin master --force
          fi
